source 'https://rubygems.org'

gem 'pry-byebug', '~> 3.5.1', platform: :mri
gem 'capybara', '~> 2.17.0'
gem 'capybara-screenshot', '~> 1.0.19'
gem 'rake', '~> 12.3.0'
gem 'rspec', '~> 3.7'
gem 'selenium-webdriver', '~> 3.8.0'
gem 'airborne', '~> 0.2.13'
